project: 
  title: Toxicant GWAS Analysis
  output-dir: _products
  execute-dir: project
  render: 
    - analysis/organize_tox_metadata.qmd
    - analysis/organize_strain_means.qmd
    - analysis/organize_strain_outliers.qmd
    - analysis/calculate_phenotype_correlations.qmd
    - paper/
execute: 
  freeze: false
  
editor: source