project: 
  title: Toxicant GWAS Analysis
  output-dir: _products
  execute-dir: project
  render: 
    - analysis/organize_tox_metadata.qmd
    - analysis/organize_strain_means.qmd
    - analysis/organize_strain_outliers.qmd
    - analysis/calculate_phenotype_correlations.qmd
    - analysis/calculate_enrich_each_interval.qmd
    - analysis/hdr_summarize_strain.qmd
    - analysis/hdr_calculate_region_overlaps.qmd
    - analysis/candidate_gene_identification.qmd
    - analysis/candidate_gene_GO.qmd
    - paper/
execute: 
  freeze: false
  
editor: source