project: 
  title: Toxicant GWAS Analysis
  output-dir: _products
  execute-dir: project
  render: 
    - analysis/nemascan_pipeline_documentation.qmd
    - analysis/decompress_nemascan_output.qmd
    - analysis/organize_tox_metadata.qmd
    - analysis/trait_generate_mapping_inputs.qmd
    - analysis/organize_strain_means.qmd
    - analysis/organize_strain_outliers.qmd
    - analysis/calculate_phenotype_correlations.qmd
    - analysis/calculate_enrich_each_interval.qmd
    - analysis/hdr_summarize_strain.qmd
    - analysis/hdr_calculate_region_overlaps.qmd
    - analysis/candidate_gene_identification.qmd
    - analysis/candidate_gene_GO.qmd
    - analysis/candidate_gene_effects.qmd
    - analysis/candidate_gene_organization.qmd
    - analysis/candidate_gene_orthologs.qmd
    - paper/
    - paper/aggregate_supplementary_tables.qmd
execute: 
  freeze: false
  
editor: source